#!/usr/bin/env bash
# GENERATED by packaging/generate.mjs from claude-plugin/. Do not edit; edit the source and re-run 'just plugin generate'.
# Cursor sessionStart hook: install or update fest and camp when a session starts.

cat >/dev/null
bash "$(dirname "$0")/ensure-festival.sh" </dev/null >&2 || true
printf '%s\n' '{}'
exit 0
