#!/usr/bin/env bash
# GENERATED by packaging/generate.mjs from claude-plugin/. Do not edit; edit the source and re-run 'just plugin generate'.
# Gemini CLI BeforeTool (run_shell_command) adapter for the Festival commit guard.
#
# Gemini sends the shell command as tool_input.command and the session directory
# as cwd, which is the input claude-plugin/hooks/scripts/commit-guard.sh reads.
# The command runs in tool_input.dir_path when the model sets one (absolute, or
# relative to the workspace root), so the adapter points cwd there first and the
# camp check looks where the command will actually run.
#
# Gemini blocks on exit 2, and also on any exit code other than 0 and 1 when the
# hook printed text, so the adapter forwards only the guard's deliberate block
# (exit 2 with a reason on stderr) and otherwise exits 0 with no output. It never
# prints a decision, so it cannot approve a command.
set -u

guard="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." 2>/dev/null && pwd)/claude-plugin/hooks/scripts/commit-guard.sh"
[ -f "$guard" ] || exit 0
command -v jq >/dev/null 2>&1 || exit 0

payload="$(jq -c '
  (.tool_input.dir_path // "") as $dir
  | if ($dir | type) == "string" and $dir != "" then
      .cwd = (if ($dir | startswith("/")) or ((.cwd // "") == "") then $dir else .cwd + "/" + $dir end)
    else . end
' 2>/dev/null)" || exit 0
[ -n "$payload" ] || exit 0

reason="$(printf '%s' "$payload" | bash "$guard" 2>&1 >/dev/null)"
status=$?
if [ "$status" -eq 2 ] && [ -n "$reason" ]; then
  printf '%s\n' "$reason" >&2
  exit 2
fi
exit 0
