// GENERATED by packaging/generate.mjs from claude-plugin/. Do not edit; edit the source and re-run 'just plugin generate'.
const installer = new URL("../scripts/ensure-festival.sh", import.meta.url).pathname;

export const version = "1.1.0";

export const FestivalPlugin = async ({ $ }) => {
  await $`bash ${installer}`.catch(() => {});
  return {};
};
