#!/usr/bin/env bash
# GENERATED by packaging/generate.mjs from claude-plugin/. Do not edit; edit the source and re-run 'just plugin generate'.
# Ensures fest and camp are installed and up-to-date. Runs on SessionStart.
# - If missing: downloads and installs from GitHub releases with checksum verification.
# - If installed: checks for newer version and offers update notification.

set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-$HOME/.local/bin}"
REPO="Obedience-Corp/festival"
CACHE_DIR="${FESTIVAL_CACHE_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/festival}"
CHECK_FILE="${FESTIVAL_CHECK_FILE:-$CACHE_DIR/last-update-check}"
DOWNLOAD_TIMEOUT_SECONDS="${FESTIVAL_DOWNLOAD_TIMEOUT_SECONDS:-120}"

info() {
    echo "$*" >&2
}

fail() {
    echo "$*" >&2
    exit 1
}

require_command() {
    local name="$1"
    command -v "$name" >/dev/null 2>&1 || fail "Required command not found: $name"
}

require_checksum_command() {
    if command -v shasum >/dev/null 2>&1 || command -v sha256sum >/dev/null 2>&1; then
        return 0
    fi

    fail "Required command not found: shasum or sha256sum"
}

check_installed() {
    command -v fest >/dev/null 2>&1 && command -v camp >/dev/null 2>&1
}

# Rate-limit update checks to once per day
should_check_update() {
    if [ ! -f "$CHECK_FILE" ]; then
        return 0
    fi
    local last_check
    last_check=$(cat "$CHECK_FILE" 2>/dev/null || echo 0)
    local now
    now=$(date +%s)
    local age=$(( now - last_check ))
    # 86400 = 24 hours
    [ "$age" -ge 86400 ]
}

record_check() {
    mkdir -p "$(dirname "$CHECK_FILE")"
    date +%s > "$CHECK_FILE"
}

detect_platform() {
    OS=$(uname -s | tr '[:upper:]' '[:lower:]')
    case "$OS" in
        darwin) OS="macOS" ;;
        linux)  OS="linux" ;;
        *)      echo "Unsupported OS: $OS" >&2; exit 1 ;;
    esac

    ARCH=$(uname -m)
    case "$ARCH" in
        x86_64|amd64)  ARCH="x86_64" ;;
        arm64|aarch64) ARCH="arm64" ;;
        *)             echo "Unsupported architecture: $ARCH" >&2; exit 1 ;;
    esac
}

fetch_release() {
    curl -fsSL --connect-timeout 10 --max-time "$DOWNLOAD_TIMEOUT_SECONDS" "https://api.github.com/repos/${REPO}/releases/latest" 2>/dev/null
}

find_archive_url() {
    local release_json="$1"
    local url

    # Try exact OS-ARCH match first, then OS-all (universal binary, e.g. macOS-all)
    url=$(echo "$release_json" | grep '"browser_download_url"' | grep -i "${OS}" | grep -i "${ARCH}" | grep '\.tar\.gz"' | head -1 | sed -E 's/.*"([^"]+)".*/\1/')

    if [ -z "$url" ]; then
        url=$(echo "$release_json" | grep '"browser_download_url"' | grep -i "${OS}" | grep -i "all" | grep '\.tar\.gz"' | head -1 | sed -E 's/.*"([^"]+)".*/\1/')
    fi

    echo "$url"
}

extract_tag() {
    echo "$1" | grep '"tag_name"' | head -1 | sed -E 's/.*"([^"]+)".*/\1/'
}

download_file() {
    local url="$1"
    local dest="$2"
    local tmp="${dest}.tmp"

    rm -f "$tmp"
    curl -fsSL --connect-timeout 10 --max-time "$DOWNLOAD_TIMEOUT_SECONDS" "$url" -o "$tmp" || {
        rm -f "$tmp"
        return 1
    }
    mv "$tmp" "$dest"
}

checksum_url_for_archive() {
    local archive_url="$1"
    echo "${archive_url%/*}/checksums.txt"
}

sha256_file() {
    local file="$1"

    if command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$file" | awk '{print $1}'
        return 0
    fi

    sha256sum "$file" | awk '{print $1}'
}

expected_checksum() {
    local checksums_file="$1"
    local archive_name="$2"

    awk -v name="$archive_name" '$2 == name {print $1; found=1} END {exit found ? 0 : 1}' "$checksums_file"
}

verify_checksum() {
    local archive_path="$1"
    local checksums_path="$2"
    local archive_name="$3"
    local expected actual

    expected="$(expected_checksum "$checksums_path" "$archive_name")" || {
        echo "Checksum for ${archive_name} not found in checksums.txt" >&2
        return 1
    }

    actual="$(sha256_file "$archive_path")"
    if [ "$actual" != "$expected" ]; then
        echo "Checksum mismatch for ${archive_name}" >&2
        echo "expected: ${expected}" >&2
        echo "actual:   ${actual}" >&2
        return 1
    fi
}

download_and_install() {
    local archive_url="$1"
    local archive_name checksums_url archive_path checksums_path

    archive_name="$(basename "$archive_url")"
    checksums_url="$(checksum_url_for_archive "$archive_url")"
    TMP_DIR=$(mktemp -d "${TMPDIR:-/tmp}/festival-plugin.XXXXXX")
    trap 'rm -rf "$TMP_DIR"' EXIT
    archive_path="${TMP_DIR}/${archive_name}"
    checksums_path="${TMP_DIR}/checksums.txt"

    download_file "$archive_url" "$archive_path" ||
        fail "Download failed. Install manually: curl -fsSL https://raw.githubusercontent.com/${REPO}/main/install.sh | bash"

    download_file "$checksums_url" "$checksums_path" ||
        fail "Checksum download failed. Install manually: curl -fsSL https://raw.githubusercontent.com/${REPO}/main/install.sh | bash"

    verify_checksum "$archive_path" "$checksums_path" "$archive_name" ||
        fail "Checksum verification failed. Install manually: curl -fsSL https://raw.githubusercontent.com/${REPO}/main/install.sh | bash"

    tar -xzf "$archive_path" -C "$TMP_DIR"

    mkdir -p "$INSTALL_DIR"
    for binary in fest camp; do
        extracted_path="$(find "$TMP_DIR" -type f -name "$binary" | head -1)"
        if [ -n "$extracted_path" ]; then
            install -m 0755 "$extracted_path" "${INSTALL_DIR}/${binary}"
        else
            fail "${binary} not found in ${archive_name}"
        fi
    done
}

# parse_local_fest_version SHORT_OUTPUT FULL_OUTPUT
#
# Prefer `fest version --short` (a single token: "dev", "v0.2.16", ...). If that
# is empty (old binary, flag unknown), take field 2 of the first `fest version`
# line ("fest v0.2.16" / "fest dev"). Do not scan the whole block for X.Y.Z:
# the Go runtime line is `go: go1.26.4` and a greedy grep treats 1.26.4 as the
# installed festival version.
parse_local_fest_version() {
    local short="${1-}"
    local full="${2-}"
    local token
    token="$(printf '%s\n' "$short" | awk 'NR==1 {print $1; exit}')"
    if [ -n "$token" ]; then
        printf '%s' "$token"
        return 0
    fi
    printf '%s\n' "$full" | awk 'NR==1 {print $2; exit}'
}

# is_release_version TOKEN: 0 when TOKEN is a festival release semver
# (optional leading v, X.Y.Z, optional -rc.N / dotted suffix). Rejects "dev",
# empty, and *-dev.* snapshot builds.
is_release_version() {
    local v="${1-}"
    case "$v" in
        ""|dev|unknown) return 1 ;;
        *-dev|*-dev.*) return 1 ;;
    esac
    printf '%s' "$v" | grep -Eq '^v?[0-9]+\.[0-9]+\.[0-9]+([.-][A-Za-z0-9.]+)?$'
}

read_local_fest_version() {
    local short full
    short="$(fest version --short 2>/dev/null || true)"
    full="$(fest version 2>/dev/null || true)"
    parse_local_fest_version "$short" "$full"
}

main() {
    require_command curl
    require_command tar
    require_command grep
    require_command sed
    require_command awk
    require_command find
    require_command install
    require_checksum_command
    detect_platform

    if ! check_installed; then
        info "Festival CLI not found. Installing fest and camp..."

        RELEASE_JSON=$(fetch_release) || {
            info "Could not fetch release info. Install manually: curl -fsSL https://raw.githubusercontent.com/${REPO}/main/install.sh | bash"
            exit 1
        }

        ARCHIVE_URL=$(find_archive_url "$RELEASE_JSON")
        if [ -z "$ARCHIVE_URL" ]; then
            info "No compatible archive found for ${OS}/${ARCH}. Install manually: curl -fsSL https://raw.githubusercontent.com/${REPO}/main/install.sh | bash"
            exit 1
        fi

        download_and_install "$ARCHIVE_URL"
        record_check

        if command -v fest >/dev/null 2>&1; then
            info "Festival installed successfully: $(fest version 2>/dev/null || echo 'fest ready')"
        else
            info "Installed to ${INSTALL_DIR}. You may need to add it to your PATH: export PATH=\"${INSTALL_DIR}:\$PATH\""
        fi
        exit 0
    fi

    # Already installed: check for updates (rate-limited to once/day)
    if ! should_check_update; then
        exit 0
    fi

    CURRENT_VERSION="$(read_local_fest_version)"
    if ! is_release_version "$CURRENT_VERSION"; then
        if [ -n "$CURRENT_VERSION" ]; then
            info "Festival update check skipped: local fest version '${CURRENT_VERSION}' is not a release"
        fi
        record_check
        exit 0
    fi

    RELEASE_JSON=$(fetch_release 2>/dev/null) || {
        record_check
        exit 0
    }

    LATEST_TAG=$(extract_tag "$RELEASE_JSON")
    CURRENT_CLEAN="${CURRENT_VERSION#v}"
    LATEST_CLEAN="${LATEST_TAG#v}"

    record_check

    if [ "$CURRENT_CLEAN" != "$LATEST_CLEAN" ]; then
        info "Festival update available: ${CURRENT_VERSION} -> ${LATEST_TAG}. Run: curl -fsSL https://raw.githubusercontent.com/${REPO}/main/install.sh | bash"
    fi
}

# Run main only when executed, not when sourced by the test harness.
if [ "${BASH_SOURCE[0]:-$0}" = "$0" ]; then
    main "$@"
fi
