#!/usr/bin/env node
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const PACKAGING_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(PACKAGING_DIR, "..");
const PLUGIN_DIR = join(REPO_ROOT, "claude-plugin");
const TARGETS_DIR = join(PACKAGING_DIR, "targets");

const BANNER =
  "GENERATED by packaging/generate.mjs from claude-plugin/. Do not edit; edit the source and re-run 'just plugin generate'.";

function parseArgs(argv) {
  let out = null;
  let listManifests = false;
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--out") out = argv[++i];
    else if (argv[i].startsWith("--out=")) out = argv[i].slice("--out=".length);
    else if (argv[i] === "--manifests") listManifests = true;
  }
  return { out, listManifests };
}

function frontmatter(text) {
  const out = {};
  if (!text.startsWith("---")) return out;
  const end = text.indexOf("\n---", 3);
  if (end === -1) return out;
  for (const line of text.slice(3, end).split("\n")) {
    const match = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (match) out[match[1]] = match[2].trim();
  }
  return out;
}

function readSkills() {
  const dir = join(PLUGIN_DIR, "skills");
  return readdirSync(dir)
    .filter((name) => statSync(join(dir, name)).isDirectory())
    .sort()
    .map((name) => {
      const meta = frontmatter(readFileSync(join(dir, name, "SKILL.md"), "utf8"));
      return { name, description: meta.description ?? "", path: `skills/${name}/SKILL.md` };
    });
}

function readDocs(sub) {
  const dir = join(PLUGIN_DIR, sub);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((file) => file.endsWith(".md"))
    .sort()
    .map((file) => {
      const meta = frontmatter(readFileSync(join(dir, file), "utf8"));
      const name = file.replace(/\.md$/, "");
      return { name, description: meta.description ?? "", path: `${sub}/${file}` };
    });
}

function makeContext(generated, outRoot) {
  const banner = BANNER;
  return {
    repoRoot: REPO_ROOT,
    outRoot,
    pluginDir: PLUGIN_DIR,
    packagingDir: PACKAGING_DIR,
    banner,
    manifest: JSON.parse(readFileSync(join(PLUGIN_DIR, ".claude-plugin", "plugin.json"), "utf8")),
    skills: readSkills(),
    commands: readDocs("commands"),
    agents: readDocs("agents"),
    sourceHooks: JSON.parse(readFileSync(join(PLUGIN_DIR, "hooks", "hooks.json"), "utf8")),
    templatePath: (harness, ext) => join(TARGETS_DIR, `${harness}.template.${ext}`),
    readTemplate: (harness, ext) => readFileSync(join(TARGETS_DIR, `${harness}.template.${ext}`), "utf8"),
    readTemplateJSON: (harness) =>
      JSON.parse(readFileSync(join(TARGETS_DIR, `${harness}.template.json`), "utf8")),
    writeJSON(relPath, obj) {
      const filePath = join(outRoot, relPath);
      mkdirSync(dirname(filePath), { recursive: true });
      writeFileSync(filePath, JSON.stringify(obj, null, 2) + "\n");
      generated.push(relPath);
    },
    writeText(relPath, body, commentPrefix) {
      const filePath = join(outRoot, relPath);
      mkdirSync(dirname(filePath), { recursive: true });
      const header = commentPrefix ? `${commentPrefix} ${banner}\n` : "";
      const text = body.endsWith("\n") ? body : `${body}\n`;
      writeFileSync(filePath, header + text);
      generated.push(relPath);
    },
  };
}

const sharedTarget = {
  harness: "shared",
  manifests: [],
  emit(ctx) {
    ctx.writeJSON("hooks/hooks.json", {
      _generated: ctx.banner,
      ...ctx.sourceHooks,
    });
  },
};

async function loadTargets() {
  if (!existsSync(TARGETS_DIR)) return [];
  const files = readdirSync(TARGETS_DIR).filter((file) => file.endsWith(".target.mjs")).sort();
  const targets = [];
  for (const file of files) {
    const mod = await import(pathToFileURL(join(TARGETS_DIR, file)).href);
    const target = mod.default;
    if (target && typeof target.emit === "function") targets.push(target);
  }
  return targets;
}

async function main() {
  const { out, listManifests } = parseArgs(process.argv.slice(2));
  const targets = [sharedTarget, ...(await loadTargets())];

  if (listManifests) {
    const manifests = targets
      .flatMap((target) => target.manifests ?? [])
      .sort()
      .map((rel) => join(REPO_ROOT, rel));
    for (const file of manifests) console.log(file);
    return;
  }

  const outRoot = out ? resolve(out) : REPO_ROOT;
  const generated = [];
  const ctx = makeContext(generated, outRoot);

  console.log(
    `source: ${ctx.skills.length} skills, ${ctx.commands.length} commands, ${ctx.agents.length} agents (v${ctx.manifest.version})`,
  );
  for (const target of targets) target.emit(ctx);

  console.log(`generated ${generated.length} file(s) into ${outRoot} from ${targets.length} target(s):`);
  for (const file of generated.sort()) console.log(`  ${file}`);
}

main().catch((error) => {
  console.error(error.message);
  process.exitCode = 1;
});
